#!/usr/bin/env python3
"""MT and WA_KING legacy parcel cleanup — phase 2 of the April 13 cleanup.

Same pattern as AZ_MARICOPA but these markets have the added wrinkle of
246 + 29 investigation_cache entries keyed to prefixed parcel IDs. The
ON DELETE CASCADE on investigation_cache.parcel_id means deleting the
prefixed parcels will also delete those cache entries. The cache will be
regenerated by the next batch run via batch/worker.js Deep Signal fresh-
investigation path (commit 3e3fc12). Cost to regenerate: ~4,500 searches
(15% of monthly quota).

This cleanup trades "free existing cache" for "clean schema + cache rebuilds
via current pipeline with fresh data." The tradeoff is worth it because:
  1. The existing cache data is from April 4 under an older truth_hash
  2. Parcels in current Act Today aren't the same parcels that were in cache
  3. Keeping stale cache entries keyed to orphan parcels creates FK mess
  4. Batch/worker.js will regenerate richer cache with raw search results in
     the long run (post-beta improvement)

MT verification completed before running:
  - 246 prefixed investigation_cache entries, all MT-06XXX format
  - 0 collisions with existing naked-ID cache entries
  - 0 naked equivalents missing from parcels table
  - Strip-MT- maps to valid naked APN IDs
  - Example: MT-06033803240030000 → 06033803240030000 (LOPEZ PHILLIP & KARLA TRUST)

WA_KING verification:
  - 29 prefixed investigation_cache entries, all WA_KING-XXXXXXXXXX format
  - 8 collisions (naked IDs already have newer cache entries) — those are
    safe because cascade only deletes the prefixed row's reference
  - 0 naked equivalents missing from parcels table

AZ_MARICOPA has NO investigation_cache entries at all so its cleanup
(already executed via 2026-04-13-cleanup-legacy-prefixed-parcels.py)
didn't need this extra care.
"""

import os, urllib.request, urllib.parse, json, sys

SB = "https://eeqsbvizgpuehphiaslo.supabase.co"
KEY = os.environ.get("SUPABASE_SERVICE_KEY", "")
if not KEY:
    print("SUPABASE_SERVICE_KEY env var required", file=sys.stderr)
    sys.exit(2)

def q(path, method='GET'):
    headers = {"apikey": KEY, "Authorization": f"Bearer {KEY}"}
    if method == 'DELETE':
        headers["Prefer"] = "return=representation"
    req = urllib.request.Request(f"{SB}/rest/v1/{path}", headers=headers, method=method)
    r = urllib.request.urlopen(req, timeout=60)
    raw = r.read()
    return json.loads(raw) if raw else None

def qcount(path):
    headers = {"apikey": KEY, "Authorization": f"Bearer {KEY}",
               "Prefer": "count=exact", "Range": "0-0"}
    req = urllib.request.Request(f"{SB}/rest/v1/{path}", headers=headers)
    r = urllib.request.urlopen(req, timeout=30)
    cr = r.headers.get('content-range', '0-0/0')
    return int(cr.split('/')[-1]) if '/' in cr else 0

def cleanup_market(market_name, prefix, zips):
    print()
    print("=" * 70)
    print(f"{market_name} LEGACY PARCEL CLEANUP")
    print("=" * 70)
    
    # Pre-check
    # Note: we scope ALL the like queries to a specific ZIP to avoid full-table
    # scan timeouts. PostgreSQL/PostgREST has a statement timeout and an
    # unindexed LIKE across the whole parcels table blows it out.
    total_cache_affected = qcount(f"investigation_cache?parcel_id=like.{prefix}*&select=parcel_id")
    print(f"  investigation_cache rows to cascade-delete: {total_cache_affected}")
    
    # Safety: naked versions exist. Use the first ZIP for sampling.
    first_zip = zips[0]
    sample = q(f"parcels?zip_code=eq.{first_zip}&id=like.{prefix}*&select=id&limit=1")
    if not sample:
        print(f"  No prefixed rows found in {first_zip} — nothing to do")
        return
    naked_sample = sample[0]['id'][len(prefix):]
    naked_check = q(f"parcels?id=eq.{naked_sample}&select=id")
    if not naked_check:
        print(f"  ❌ ABORT: naked equivalent '{naked_sample}' not in parcels table. Prefix strip may be wrong.")
        return
    print(f"  ✓ Prefix-strip verified: {sample[0]['id']} → {naked_sample} exists in parcels")
    
    # Count per-ZIP
    print(f"\nCount per ZIP:")
    total_to_delete = 0
    per_zip = {}
    for zc in zips:
        c = qcount(f"parcels?zip_code=eq.{zc}&id=like.{prefix}*&select=id")
        per_zip[zc] = c
        total_to_delete += c
        print(f"    {zc}: {c} prefixed rows")
    print(f"  Total to delete: {total_to_delete}")
    
    if total_to_delete == 0:
        print(f"  Nothing to delete")
        return
    
    # Execute
    print(f"\nExecuting DELETE per ZIP...")
    total_deleted = 0
    for zc in zips:
        if per_zip[zc] == 0:
            continue
        try:
            result = q(f"parcels?zip_code=eq.{zc}&id=like.{prefix}*", method='DELETE')
            deleted = len(result) if result else 0
            total_deleted += deleted
            print(f"  {zc}: deleted {deleted}")
        except Exception as e:
            print(f"  {zc}: FAILED {e}")
            sys.exit(1)
    print(f"  Total deleted: {total_deleted}")
    
    # Post-check
    print(f"\nPost-delete verification:")
    for zc in zips:
        remaining = qcount(f"parcels?zip_code=eq.{zc}&id=like.{prefix}*&select=id")
        total_remaining = qcount(f"parcels?zip_code=eq.{zc}&select=id")
        print(f"  {zc}: {total_remaining} total, {remaining} prefixed remaining")
    
    cache_remaining = qcount(f"investigation_cache?parcel_id=like.{prefix}*&select=parcel_id")
    print(f"  investigation_cache {prefix}* remaining: {cache_remaining}")

# MT — 6 ZIPs
MT_ZIPS = ['59715','59718','59716','59730','59711','59714']
cleanup_market('MT', 'MT-', MT_ZIPS)

# WA_KING — 10 ZIPs
WA_KING_ZIPS = ['98004','98033','98039','98040','98074','98103','98105','98109','98112','98199']
cleanup_market('WA_KING', 'WA_KING-', WA_KING_ZIPS)

print()
print("=" * 70)
print("✓ MT + WA_KING CLEANUP COMPLETE")
print("=" * 70)
print()
print("Next: trigger batches for 59715 and 98004 to repopulate investigation_cache:")
print("  curl 'https://sellersignal.co/api/batch/start?key=ss_batch_2026&zip=59715'")
print("  curl 'https://sellersignal.co/api/batch/start?key=ss_batch_2026&zip=98004'")
